<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>KeepAwakeTool.Platform.Win</RootNamespace>
    <AssemblyName>KeepAwakeTool.Platform.Win</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KeepAwakeTool.Core\KeepAwakeTool.Core.csproj" />
  </ItemGroup>
</Project>
