<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>KeepAwakeTool.App</RootNamespace>
    <AssemblyName>KeepAwakeTool</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseAvalonia>true</UseAvalonia>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Tray/Assets/*.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KeepAwakeTool.Core\KeepAwakeTool.Core.csproj" />
    <ProjectReference Include="..\KeepAwakeTool.Platform.Win\KeepAwakeTool.Platform.Win.csproj" />
    <PackageReference Include="Avalonia" Version="12.0.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3" />
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.8" />
  </ItemGroup>
</Project>
